### ISSUE TITLE
Make this project easy to maintain

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/chano4mayor#32]
I think we should make sure this repo has all the information in it to make sure we can jump back in easily in the future.

- [x] Beef up the readme
    - [x] Expand info about dev tools/installation/dependencies
    - [x] Add info about git usage/branching strategy
    - [x] Add style guidelines
    - [x] Add info about deployment
- [ ] Clean up and comment the scss

**Comment by jeancochrane** [comment]
I got bullets 1-3!

**Comment by jeancochrane** [comment]
First three bullets are knocked out in [691848b](https://github.com/jeancochrane/chano4mayor/commit/691848b776974a02ddeba4fc455bc543f41a41fb). Take a look and see what I forgot! In particular, there may be Grunt- or npm-specific dependencies that I neglected to list.

I'd vote to axe bullet 5 (info about deployment) – I used the DataMade deploy flow to set this up, so there's no chance I'll forget! I'd also rather not advertise our deployment strategies in case of any security risks (although I admit our threat level is pretty low).

Otherwise, I leave the style guidelines and SCSS comments to you.

**Comment by kalilsn** [comment]
Great! There are a few small text changes and one typo I found that I'm gonna fix but it looks amazing.

RE: Deployment info, I think we should still include it because anyone who's looking to exploit it can already see our travis setup. I know you won't forget, but I will!

**Comment by jeancochrane** [comment]
OK! Deploy instructions are in as of [3aa5788.](https://github.com/jeancochrane/chano4mayor/commit/3aa5788254f689bd7b86cdd5afc576e61b84feb1)

**Comment by kalilsn** [comment]
Thanks! Fixed a few typos, added more dependencies, and a brief style section. LMK if you disagree.

**Comment by jeancochrane** [comment]
Looks great! Close whenever you feel satisfied with the CSS documentation.
