### ISSUE TITLE
Figure out embedded audio

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#4]
We should link directly to the songs for quotes.

[SoundCite](https://soundcite.knightlab.com/) will be useful for this.

**Comment by jeancochrane** [comment]
Great job getting these embedded @kalilsn! Can we clip them so that they start at the quote in question? It's fine for them to run on after that (some people (i.e. me) will probably want to listen to the rest of it after hearing a clip) but I think it'd be more satisfying to be able to hear the line immediately.

**Comment by kalilsn** [comment]
Interesting. I agree that it's nice to hear the quote immediately but I also really like to actually be able to listen to the song (especially on a page with so much text, it's fun to leave it on in the background). Since there's no controls on the player I thought it would be better this way.

I kind of think the ideal thing would be for it to play the quote, then just start playing the full song after, from the beginning. I'm not sure if that's possible but it seems like we could maybe tinker with soundcite a bit? What do you think @beamalsky @alexsoble?

**Comment by beamalsky** [comment]
I'd also voted for playing the whole song from the beginning. It feels really nice to me to be able to listen to the whole thing while you scroll, and also to try to find the pulled quote. That also means that we're presenting them as he released them, not in sound bite form, which I think is both truer to the idea of the site and sounds better—we're not twisting his words, just presenting how good his music is.

**Comment by beamalsky** [comment]
(also bc i'm so into the way he introduces himself in Somewhere in Paradise!!)

**Comment by jeancochrane** [comment]
I'm convinced! Closing this.
